services:
  db:
    image: mongo
    volumes:
      - dbdata:/data/db
    logging:
      driver: none
  ngrok:
    container_name: master-server-ngrok-1
    image: wernight/ngrok
    environment:
      - NGROK_AUTH=${NGROK_AUTH_TOKEN}
    ports:
      - "8081:8081"
      - "4040:4040"
    command:
      - /bin/sh
      - -c
      - |
        ngrok start --all
    volumes:
      - .:/home/ngrok/.ngrok2/
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh ./start_prod.sh
    environment:
      - IS_DOCKER_COMPOSE=true
      - NODE_ENV=production
      # - DOCKER_HOST_IP=${DOCKER_HOST_IP}
      - DOCKER_HOST_IP
    ports:
      - "8000-8080:8000-8080"
      - "8082-9000:8082-9000"
      - "12345:12345/udp"
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  dbdata: {}
